FROM openjdk:11

WORKDIR /app

COPY src/main/resources/application.properties /app/application.properties


authenticationcontroller , authenticationrequest authenticationresponse , authenticationservice, registerationrequest,
addtocartrequest, cartcontroller, cartresponse, cartservice, removecartitemrequest, cloudinaryservice, cloudinaryserviceimpl,
menuitemcontroller, menuitemmodel, menuitemservice, menuitemserviceimpl, baseentity,  applicationauditaware, beansconfig,
cloudinaryconfiguration, datarestconfig , cartitemrepository, cartrepository, categoryrepository, imagerepository,
menuitemrepository, orderitemrepository, orderrepository, shippingaddressrepositoy, emailservice, emailtemplatename, cart,cartitem, category,
image,menuitem, order, orderitem, shippingaddress, activationtokenexception, operationnotpermittedexception, ordercontroller,
orderservice, role, rolerepository, jwtfilter, jwtservice, securityconfig, userdetailsserviceimpl, token, tokenrepository, user, userrepository